/*
 *  Automatically generated by genbuiltins.py, do not edit!
 */

#ifndef __DUK_BUILTINS_H
#define __DUK_BUILTINS_H 1

extern duk_c_function duk_builtin_native_functions[];

extern char duk_builtins_data[];

#define  DUK_BUILTINS_DATA_LENGTH                                      1163

#define  DUK_BIDX_GLOBAL                                               0
#define  DUK_BIDX_GLOBAL_ENV                                           1
#define  DUK_BIDX_OBJECT_CONSTRUCTOR                                   2
#define  DUK_BIDX_OBJECT_PROTOTYPE                                     3
#define  DUK_BIDX_FUNCTION_CONSTRUCTOR                                 4
#define  DUK_BIDX_FUNCTION_PROTOTYPE                                   5
#define  DUK_BIDX_ARRAY_CONSTRUCTOR                                    6
#define  DUK_BIDX_ARRAY_PROTOTYPE                                      7
#define  DUK_BIDX_STRING_CONSTRUCTOR                                   8
#define  DUK_BIDX_STRING_PROTOTYPE                                     9
#define  DUK_BIDX_BOOLEAN_CONSTRUCTOR                                  10
#define  DUK_BIDX_BOOLEAN_PROTOTYPE                                    11
#define  DUK_BIDX_NUMBER_CONSTRUCTOR                                   12
#define  DUK_BIDX_NUMBER_PROTOTYPE                                     13
#define  DUK_BIDX_DATE_CONSTRUCTOR                                     14
#define  DUK_BIDX_DATE_PROTOTYPE                                       15
#define  DUK_BIDX_REGEXP_CONSTRUCTOR                                   16
#define  DUK_BIDX_REGEXP_PROTOTYPE                                     17
#define  DUK_BIDX_ERROR_CONSTRUCTOR                                    18
#define  DUK_BIDX_ERROR_PROTOTYPE                                      19
#define  DUK_BIDX_EVAL_ERROR_CONSTRUCTOR                               20
#define  DUK_BIDX_EVAL_ERROR_PROTOTYPE                                 21
#define  DUK_BIDX_RANGE_ERROR_CONSTRUCTOR                              22
#define  DUK_BIDX_RANGE_ERROR_PROTOTYPE                                23
#define  DUK_BIDX_REFERENCE_ERROR_CONSTRUCTOR                          24
#define  DUK_BIDX_REFERENCE_ERROR_PROTOTYPE                            25
#define  DUK_BIDX_SYNTAX_ERROR_CONSTRUCTOR                             26
#define  DUK_BIDX_SYNTAX_ERROR_PROTOTYPE                               27
#define  DUK_BIDX_TYPE_ERROR_CONSTRUCTOR                               28
#define  DUK_BIDX_TYPE_ERROR_PROTOTYPE                                 29
#define  DUK_BIDX_URI_ERROR_CONSTRUCTOR                                30
#define  DUK_BIDX_URI_ERROR_PROTOTYPE                                  31
#define  DUK_BIDX_MATH                                                 32
#define  DUK_BIDX_JSON                                                 33
#define  DUK_BIDX_TYPE_ERROR_THROWER                                   34
#define  DUK_BIDX_DUK                                                  35
#define  DUK_BIDX_THREAD_PROTOTYPE                                     36
#define  DUK_BIDX_DOUBLE_ERROR                                         37

#define  DUK_NUM_BUILTINS                                              38

#endif  /* __DUK_BUILTINS_H */
